import { AxiosError } from 'axios';
import { tesloApi } from '../api/tesloApi';

// Generated by https://quicktype.io

export interface LoginResponse {
  id:       string;
  email:    string;
  fullName: string;
  isActive: boolean;
  roles:    string[];
  token:    string;
}


export class AuthService {


  static loginUser = async (email: string, password: string) => {
    try {
      const resp = await tesloApi.post<LoginResponse>('/auth/login', { email, password });
 
      console.log(resp.data);
     return resp.data;
      
    } catch (error) {
      if ( error instanceof AxiosError ) {
        console.log(error.response?.data);
        throw new Error(error.response?.data.msg);
      }

      console.log(error);
      throw new Error('Unable to login');
    }

  }


}